export const window =require('./1.png');
export const washing_machine =require('./2.png');
export const cabinate=require('./3.png');
export const oven =require('./4.png');
export const fridge =require('./5.png');
export const broom = require('./broom.png');
export const brush = require('./brush.png');
export const mop = require('./mop.png');
export const nosel = require('./nosel.png');
export const spray = require('./spray.png');
export const vaccum = require('./vaccum.png');
// export const =require('./about.png');
export const add =require('./add.png');
export const down_arrow =require('./admin-arrow.png');
export const blue_calendar =require('./admin-calendar-blue.png');
export const admin_arrow=require('./admin-small-arrow.png');
export const user_logo =require('./admin-user.png');
export const submit_arrow =require('./arrow-white.png');
export const become_helper=require('./become-a-pro-banner.png');
export const bgleftimg =require('./blog-left-bg.png');
export const bgrightimg =require('./blog-right-bg.png');
export const calender_transparent =require('./calendar.png');
export const calender_user =require('./calendar2.png');
export const cap =require('./cap.png');
// export const =require('./down-arrow.png');
export const facebook=require('./facebook-mobile-menu.png');
// export const =require('./faq-banner.png');
// export const =require('./first-page.png');
// export const =require('./footer-logo.png');
// export const =require('./forma-1-copy-19.png');
export const diamond =require('./forma-1-copy-5.png');
export const uparrow =require('./forma-1.png');
export const location =require('./forma-1_2.png');
// export const =require('./forma-1_3.png');
export const checkmark =require('./forma-1_5.png');
// export const =require('./grey-small-star.png');
export const map =require('./group-16.png');
// export const =require('./group-16_2.png');
export const img2=require('./group-18-round-2.png');
export const img3=require('./group-18-round-3.png');
export const img1=require('./group-18-round.png');
// export const =require('./group-18.png');
// export const =require('./group-18bg.png');
export const Int_pic1 =require('./group-18_2.png');
export const Int_pic2=require('./group-18_3.png');
export const Int_pic3=require('./group-18_4.png');
export const downscroll =require('./group-18_5.png');
export const group21 =require('./group-21.png');
export const group23=require('./group-23.png');
export const group24=require('./group-24.png');
export const group28 =require('./group-28.png');
export const group29=require('./group-29.png');
export const group30=require('./group-30.png');
export const pic1 =require('./group-31.png');
export const pic2 =require('./group-32.png');
export const pic3 =require('./group-33.png');
export const group36=require('./group-36.png');
// export const =require('./group-38.png');
// export const =require('./guarantee-banner.png');
// export const =require('./helper-img-1.png');
// export const =require('./hero-banner-img.png');
// export const =require('./home-herobanner.jpg');
export const check =require('./ic-check.png');
export const face_book =require('./ic-facebook.png');
export const flag =require('./ic-flag.png');
export const instagram=require('./ic-instagram.png');
export const notification=require('./icon-notification.png');

export const insta=require('./instagram-mobile-menu.png');
// export const =require('./keyboard-right-arrow-button-copy.png');
// export const =require('./keyboard-right-arrow-button.png');
// export const =require('./Landing-Page-background-image.png');
export const narrow_arrow=require('./layer-1025-copy-2.png');
export const watch=require('./layer-14.png');
export const House=require('./layer-15.png');
// export const =require('./layer-20.png');
export const messege =require('./layer-598.png');
// export const =require('./layer-712.png');
// export const =require('./layer-719.png');
export const logo =require('./logo-large.png');
// export const =require('./logo-small.png');
export const logout=require('./logout.png');
export const bg_messege=require('./message.png');
export const phone=require('./phone-call.png');
export const pointer =require('./pin.png');
// export const =require('./polygon-1-copy-5.png');
export const right_grey_arrow =require('./right-arrow-grey.png');
export const circle_right_arrow=require('./right-arrow.png');
// export const =require('./separator.png');
// export const =require('./shape-1.png');
export const arrow_right =require('./shape-2-copy-3.png');
export const arrow=require('./shape-2.png');
export const sort_button=require('./sort.png');
export const downarrow=require('./sp-arrow-down.png');
export const yellow_star=require('./star1.png');
export const normal_star=require('./star2.png');
export const step1 =require('./step-1.png');
export const step2=require('./step-2.png');
export const step3=require('./step-3.png');
export const step4=require('./step-4.png');
export const step_arrow_up =require('./step-arrow-1-copy.png');
export const step_arrow_dn =require('./step-arrow-1.png');
export const bestimg=require('./the-best-img-1.png');
// Thumbs.db
// export const =require('./user.png');
// export const =require('./vector-smart-object-copy.png');
export const envelope =require('./vector-smart-object.png');
// export const =require('./yellow-small-star.png');
export const dark_down_arrow =require('./dark_down_arrow.png')
export const first_last_arrow= require('./first_last_arrow.png')
export const Left_dark_arrow= require('./Left_dark_arrow.png')
export const helperland = require('./helperland.png');
export const green_window= require('./1-green.png');
export const green_machine= require('./2-green.png');
export const green_cupboard= require('./3-green.png');
export const green_oven= require('./4-green.png');
export const green_fridge= require('./5-green.png');
export const house= require('./details.png');
export const house_white= require('./details-white.png');
export const payment= require('./payment.png');
export const payment_white= require('./payment-white.png');
export const schedule= require('./schedule.png');
export const schedule_white= require('./schedule-white.png');
export const setup= require('./setup-service.png');
export const setup_white= require('./setup-service-white.png');
export const smiley= require('./smiley.png');
export const green_calendar= require('./calendar-book-service.png');
export const userLogin=require('./user_login.png')
export const lock = require('./lock.png')
export const edit = require('./edit-icon.png')
export const deleteIcon = require('./delete-icon.png')
export const largeCap = require('./large-cap.png')
export const avatarCap = require('./avatar-hat.png')
export const avatarIron = require('./avatar-iron.png')
export const avatarMale = require('./avatar-male.png')
export const avatarFemale = require('./avatar-female.png')
export const avatarCar = require('./avatar-car.png')
export const avatarShip = require('./avatar-ship.png')

